spring:
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    show-sql: ${SHOW_SQL:false}
    open-in-view: false

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}

springdoc:
  swagger-ui:
    path: /docs
  api-docs:
    path: /v3/api-docs

jwt:
  secret-key: ${SECRET_KEY}
  accessExpirationPeriod: ${EXPIRATION_PERIOD}
  issuer: ${ISSUER}

fcm: ${FCM_JSON}

google:
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}
  redirect-uri: ${REDIRECT_URI}
  token-uri: ${TOKEN_URI}
  user-info-uri: ${USER_INFO_URI}
